version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  sender:
    build: ./sender
    depends_on:
      - server
